
name: ESLint
on: [push, pull_request]
jobs:
  test:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    name: ESLinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install
      - run: npm test